[project]
name = "dell-lookup"
version = "0.1.0"
description = "Quick Dell API lookups and scripts and stuff"
readme = "README.md"
requires-python = ">=3.12.8"
dependencies = [
    "httpx>=0.28.1",
    "pandas>=2.2.3",
    "pydantic>=2.10.6",
    "python-dotenv>=1.0.1",
    "rich>=13.9.4",
]
